# Use the pre-built Eliza image
FROM gcr.io/noid-one-development/noid-eliza:latest

# Set the working directory
WORKDIR /app

# Copy character JSON and environment variables
COPY characters/character.json /app/characters/character.json
COPY .env /app/.env

# Expose port 8080 for Google Cloud Run
EXPOSE 3000 8080

# Run both the server and client concurrently
# CMD ["pnpm", "dlx", "concurrently", "pnpm start --characters=characters/character.json", "sh -c 'pnpm dlx wait-on tcp:8080 && pnpm start:client --host 0.0.0.0'"]
# CMD sh -c "pnpm exec concurrently 'pnpm start --characters=characters/character.json' 'sleep 60 && pnpm exec wait-on tcp:8080 && pnpm start:client --host 0.0.0.0'"
CMD ["sh", "-c", "pnpm start --characters=characters/character.json & pnpm start:client --host"]